name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Grant execution permission to Gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step to run Unit Tests
    - name: Run Unit Tests
      run: ./gradlew test
      continue-on-error: false  # Fail if any unit test fails
      
    # List all files and directories to locate test reports
    - name: List all files in the build folder
      run: ls -R app/build/
      
    # Upload test results as artifacts
    - name: Upload Unit Test Results
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: Unit-Test-Results
        path: app/build/reports/tests/testDebugUnitTest  # Change this path if your test results are in a different folder


    # Step to build the APK
    - name: Build with Gradle
      run: ./gradlew build

    # Step to upload APK as an artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: CryptoViewer.apk
        path: app/build/outputs/apk/debug/app-debug.apk
