name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Grant execution permission to Gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Step to run Unit Tests
    - name: Run Unit Tests
      run: ./gradlew test
      continue-on-error: false  # Fail if any unit test fails

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3
        target: default

    # Start Android Emulator
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        emulator-options: "-no-snapshot -noaudio -no-window"
        script: ./gradlew connectedAndroidTest

    # Step to build the APK
    - name: Build with Gradle
      run: ./gradlew build

    # Step to upload APK as an artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: CryptoViewer.apk
        path: app/build/outputs/apk/debug/app-debug.apk
